services:
  - type: web
    name: afford-today
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PRO_USER_IDS
        sync: false
